### PR TITLE
Changing Telemetry to be More Category-based

### PR DESCRIPTION
**Pull request by andreamah**
As written in title; causes less empty telemetry events.

### CODE REVIEW

**Review by lramos15 — CHANGES_REQUESTED** [review]
You don't quite have these GDPR annotations correct.
Here's an example of one surrounding cloning in the GitHub PR extension https://github.com/microsoft/vscode/blob/main/extensions/git/src/commands.ts#L504-L508

As you see the the event name is the top level key and then it contains all the properties inside with their classifications and purposes. My suggestion was around you having an event called `preview` and then something like `method` as the  property showing what type of preview they were in. Let me know if that helps clarify.

**Comment by andreamah** [comment]
> You don't quite have these GDPR annotations correct.
> Here's an example of one surrounding cloning in the GitHub PR extension https://github.com/microsoft/vscode/blob/main/extensions/git/src/commands.ts#L504-L508
> 
> As you see the the event name is the top level key and then it contains all the properties inside with their classifications and purposes. My suggestion was around you having an event called `preview` and then something like `method` as the property showing what type of preview they were in. Let me know if that helps clarify.
> 
> Additionally, you don't need your own setting to turn on and off telemetry as it's linked to the VS code setting. Having one is up to your extension if you wish to keep it.

Ah ok, that helps a lot! Btw, I think I linked it to the vscode setting `telemetry.enableTelemetry`, so it's not my own setting. Should I still link it, or does it happen automatically?

**Review by lramos15 — APPROVED** [review]
This looks better :). You could clean up further by condensing things like `tasks.terminal.startFromExtension` and `tasks.terminal.start` together but that's just me being a neat freak. Nice job 👍

**Comment by andreamah** [comment]
> This looks better :). You could clean up further by condensing things like `tasks.terminal.startFromExtension` and `tasks.terminal.start` together but that's just me being a neat freak. Nice job 👍

Thanks! `tasks.terminal.start` will actually register whenever `tasks.terminal.startFromExtension` is run (but vice versa is not true), so that's why I made them separate events instead of condensing them into one.

**Pull request merged**
