### PR TITLE
UX Optimizations

### PR DESCRIPTION
**Pull request by andreamah**
Addressed suggestions featured in https://github.com/microsoft/vscode/issues/125949

I made the UX look a lot more like how the simple browser looks.

[Image from Gyazo](https://gyazo.com/42fd2ee6cb7c3c44d74ff2887b1c445e)

Also modified how external links are opened:

[Image from Gyazo](https://gyazo.com/9f2be0f421439fd30065f7bba44a42f0)

Closes https://github.com/microsoft/vscode/issues/125949

### CODE REVIEW

**Comment by misolori** [comment]
This is looking great! The only comment I have is the button hover state looks different than our toolbar actions, not sure if those were intentional?

CleanShot 2021-06-11 at 08 49 40@2x

**Comment by andreamah** [comment]
> This is looking great! The only comment I have is the button hover state looks different than our toolbar actions, not sure if those were intentional?
> 
> CleanShot 2021-06-11 at 08 49 40@2x

Looks like I was using `--vscode-button-hoverBackground` in the CSS for button hover background. Do you know what the name of the property I should be using + how I can view the colour options?

**Comment by misolori** [comment]
yea the color token should be `toolbar.hoverBackground`

**Comment by andreamah** [comment]
@misolori 
I think I got it looking more like the action bar buttons with this commit?
[Image from Gyazo](https://gyazo.com/f2dbf98fd69a2344f3d8770e70aa2f53)

**Comment by misolori** [comment]
Yes, that looks great 🚀

**Pull request merged**
